apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-identity-webhook
  namespace: kube-system
webhooks:
  - name: pod-identity-webhook.amazonaws.com
    failurePolicy: Ignore
    clientConfig:
      service:
        name: pod-identity-webhook
        namespace: kube-system
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVVnpUNVN4OTVQZ1hGbTRYUnFxRDk1TWpHc0h3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tjRzlrTFdsa1pXNTBhWFI1TFhkbFltaHZiMnN1YTNWaVpTMXplWE4wWlcwdQpjM1pqTUI0WERUSXdNRFV3TXpBNU16QTFORm9YRFRJeE1EVXdNekE1TXpBMU5Gb3dMekV0TUNzR0ExVUVBd3drCmNHOWtMV2xrWlc1MGFYUjVMWGRsWW1odmIyc3VhM1ZpWlMxemVYTjBaVzB1YzNaak1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTFacTFxWVBlMEo1TDhQbWNVTU1objFON21Sdld3M09pWlphVQo5ZHhTQ210MHIwYlpYM0hWek9kNE1Bc3lJa0RjOTdQd2oyWXpKZnpieWtRRm5SaXNiQXJjSHhiZU5PM2J0MXY3CkMxa3RiVExQL1JwYWxTYjNucVIxeFBXOWxPbjVYQWM0WmdieXZUUklrSDdwc1RwM0hCVnN0aW8xT1c2RndBZnUKOXljcWh5a3hTSnUrZ1kzd0lhU2FvYkVQUW9iMEcxcEdvZFZNWS8yVlZENmlwQXdmZ3d3RVBodllwUEIvaEdTdQpHRDJkRDZuVHE2WFBram15MFAxZ1k3VHo3RTBjbFZJcFJWQ2VlSnBhemZDVzROU1RPZkxRNnVEdGJ0QmROK3JvCnlhVkM2cHVQZXFoK3BlZmRGWXJldzI2d1Q4bm9qT1JqcHVqSFF1QmFQZzNTTFY2bkV3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVaURGS2ZjSTlVVXdKOFBIN2tBV1lkQUs2Qm1rd0h3WURWUjBqQkJnd0ZvQVVpREZLZmNJOQpVVXdKOFBIN2tBV1lkQUs2Qm1rd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFJQ1Y0dFljNjIwOE82a3Vad1BLZElEUnUvVXloQ2YrQWl0cWNOeHh0ZWwza1NsMHJkd3NwWmIrWDJ4amUKU0hubDdJdnhzck80a0diQUtTQ3MxUzIzU3pXUnhwZnBFSGdMUkRjK2pmeXZsRU50UnhzbVYrWU5SZ0xRV3JxeAoybEhSTkJDY3hGZmt0MnN0OEVzNFBQTEpwcWJEWTlzdjg0UWNVSGZxUmdhZmExTU9yOUZ6a25ObVNoRytsK0t6Ck1iM3R0KzlMakJzOGVDWngxMm9kdCtPMWhPa08zNWUzRDIyaXVva09MQmVqd1VLdWFTcW56bEhjYkJmRUJwOFYKSGVaZmZxM3dEcnlGUWRINHJwV0p4RUZEOVdLM3VhNUUxbmhQS0tOYmRTYy9KMGg2T0E0WUJKMW5CUm4rUUd3SAo5WktobHh5cU15UjB5WGthSk5rUjRXLzkyZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
